// src/app/auth/page.jsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/lib/stores/auth.js';
import { useShallow } from 'zustand/react/shallow';
import { useMessagesStore } from '@/lib/stores/messages.js';
import { createSupabaseClient } from '@/lib/supabase.js';
import { keyManager } from '@/lib/crypto/key-manager.js';
import { privateKeyManager } from '@/lib/crypto/private-key-manager.js';
import { indexedDBManager } from '@/lib/crypto/indexed-db-manager.js';
import Message from '@/lib/components/Message.jsx';

export default function AuthPage() {
  const router = useRouter();
  const { user, isAuthenticated: authenticated, loading, sendSMS, verifySMS } = useAuthStore(
    useShallow((s) => ({ user: s.user, isAuthenticated: !!s.user, loading: s.loading, sendSMS: s.sendSMS, verifySMS: s.verifySMS }))
  );
  const msgs = useMessagesStore((s) => s.messages);
  const removeMsg = useMessagesStore((s) => s.remove);

  const [step, setStep] = useState('phone');
  const [verifying, setVerifying] = useState(false);
  const [phoneNumber, setPhoneNumber] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [username, setUsername] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [countdown, setCountdown] = useState(0);
  const [canResend, setCanResend] = useState(true);
  const [verifiedSession, setVerifiedSession] = useState(null);
  const [avatarUrl, setAvatarUrl] = useState(null);
  const [backupPin, setBackupPin] = useState('');
  const [confirmBackupPin, setConfirmBackupPin] = useState('');
  const [showBackupPin, setShowBackupPin] = useState(false);
  const [restorePin, setRestorePin] = useState('');
  const [showRestorePin, setShowRestorePin] = useState(false);
  const [isRestoring, setIsRestoring] = useState(false);
  const [restoreAttempts, setRestoreAttempts] = useState(0);
  const MAX_RESTORE = 5;
  const msgStore = useMessagesStore.getState();

  useEffect(() => {
    if (authenticated) router.replace('/chat');
  }, [authenticated]);

  function formatPhoneNumber(value) {
    const clean = value.replace(/[^\d+]/g, '');
    if (clean.length > 0 && !clean.startsWith('+')) return '+' + clean;
    return clean;
  }

  function startCountdown(seconds) {
    setCountdown(seconds);
    setCanResend(false);
    const interval = setInterval(() => {
      setCountdown((c) => {
        if (c <= 1) { clearInterval(interval); setCanResend(true); return 0; }
        return c - 1;
      });
    }, 1000);
  }

  async function handleSendSMS(e) {
    e?.preventDefault();
    if (!phoneNumber.trim()) return;
    const result = await sendSMS(phoneNumber);
    if (result.success) {
      setStep('verify');
      startCountdown(60);
    }
  }

  async function handleVerifySMS(e) {
    e?.preventDefault();
    if (verificationCode.length !== 6 || verifying || loading) return;
    setVerifying(true);
    const result = await verifySMS(phoneNumber, verificationCode);
    if (!result.success && !result.requiresUsername) setVerifying(false);

    if (result.success) {
      if (result.isNewUser) {
        router.push('/chat');
      } else {
        const sessionToken = result.session?.access_token;
        const authHeaders = sessionToken ? { 'Authorization': `Bearer ${sessionToken}` } : {};
        try {
          const hasLocalKeys = await indexedDBManager.get('qryptchat_pq_keypair');
          const backupRes = await fetch('/api/auth/key-backup', { headers: authHeaders });
          const hasBackup = backupRes.ok;
          const pinCheckRes = await fetch('/api/auth/backup-pin', { headers: authHeaders });
          const pinData = pinCheckRes.ok ? await pinCheckRes.json() : { hasPin: false };
          if (hasBackup && !hasLocalKeys) {
            setVerifiedSession(result.session);
            setStep('restore');
            return;
          }
          if (!pinData.hasPin && hasLocalKeys) {
            setVerifiedSession(result.session);
            setStep('backup');
            return;
          }
        } catch { setVerifiedSession(result.session); setStep('restore'); return; }
        router.push('/chat');
      }
    } else if (result.requiresUsername) {
      setVerifiedSession(result.session);
      setStep('profile');
    }
  }

  function handleCodeInput(e) {
    const val = e.target.value.replace(/\D/g, '').slice(0, 6);
    setVerificationCode(val);
    if (val.length === 6) setTimeout(handleVerifySMS, 100);
  }

  async function completeProfile(e) {
    e?.preventDefault();
    if (!username.trim() || !verifiedSession?.access_token) return;
    try {
      const headers = { 'Authorization': `Bearer ${verifiedSession.access_token}`, 'Content-Type': 'application/json' };
      const res = await fetch('/api/auth/verify-sms', { method: 'POST', headers, body: JSON.stringify({ phoneNumber, username, displayName: displayName || username, useSession: true }) });
      const data = await res.json();
      if (res.ok && data.success) {
        localStorage.setItem('qrypt_user', JSON.stringify(data.user));
        localStorage.setItem('supabase.auth.token', JSON.stringify(verifiedSession));
        const supabase = createSupabaseClient();
        await supabase.auth.setSession(verifiedSession);
        try {
          await keyManager.generateUserKeys();
          setStep('backup');
          msgStore.success('Account created! Please set a Backup PIN.');
        } catch { msgStore.warning('Account created but failed to generate encryption keys.'); router.push('/chat'); }
      } else { msgStore.error(data.error || 'Failed to create account'); }
    } catch { msgStore.error('Failed to create account. Please try again.'); }
  }

  async function setBackupPinFn(e) {
    e?.preventDefault();
    if (!backupPin || !/^\d+$/.test(backupPin) || backupPin.length < 6 || backupPin.length > 12) { msgStore.error('PIN must be 6-12 digits'); return; }
    if (backupPin !== confirmBackupPin) { msgStore.error('PINs do not match'); return; }
    try {
      const headers = { 'Content-Type': 'application/json' };
      if (verifiedSession?.access_token) headers['Authorization'] = `Bearer ${verifiedSession.access_token}`;
      const pinRes = await fetch('/api/auth/backup-pin', { method: 'POST', headers, body: JSON.stringify({ pin: backupPin }) });
      if (!pinRes.ok) { const err = await pinRes.json().catch(() => ({})); throw new Error(err.error || 'Failed to save PIN'); }
      const encryptedData = await privateKeyManager.exportPrivateKeys(backupPin);
      const backupHeaders = { 'Content-Type': 'application/json' };
      if (verifiedSession?.access_token) backupHeaders['Authorization'] = `Bearer ${verifiedSession.access_token}`;
      const backupRes = await fetch('/api/auth/key-backup', { method: 'PUT', headers: backupHeaders, body: JSON.stringify({ encrypted_keys: encryptedData }) });
      if (!backupRes.ok) { const e = await backupRes.json().catch(() => ({})); throw new Error(e.error || 'Key backup failed'); }
      msgStore.success('Backup PIN set and keys backed up! Welcome to QryptChat!');
      router.push('/chat');
    } catch (err) { msgStore.error('Failed to set backup PIN: ' + (err.message || 'Unknown error')); }
  }

  async function restoreWithPin(e) {
    e?.preventDefault();
    if (!restorePin || restoreAttempts >= MAX_RESTORE) return;
    setIsRestoring(true);
    try {
      await privateKeyManager.restoreKeysFromServer(restorePin);
      msgStore.success('Encryption keys restored successfully!');
      setRestorePin(''); setRestoreAttempts(0);
      router.push('/chat');
    } catch {
      const remaining = MAX_RESTORE - restoreAttempts - 1;
      setRestoreAttempts((a) => a + 1);
      setRestorePin('');
      if (remaining <= 0) msgStore.error('Too many failed attempts.');
      else msgStore.error(`Wrong PIN. ${remaining} attempt${remaining === 1 ? '' : 's'} remaining.`);
    } finally { setIsRestoring(false); }
  }

  return (
    <div className="auth-container">
      <div className="auth-card">
        <div className="auth-header">
          <div className="logo"><div className="logo-icon">🔐</div><h1>QryptChat</h1></div>
          <p className="subtitle">Secure, quantum-resistant messaging</p>
        </div>

        <div className="messages-container">
          {msgs.map((m) => <Message key={m.id} type={m.type} message={m.message} title={m.title} dismissible={m.dismissible} autoDismiss={m.autoDismiss} onDismiss={() => removeMsg(m.id)} />)}
        </div>

        {step === 'phone' && (
          <div className="auth-step">
            <h2>Enter your phone number</h2>
            <p className="step-description">We'll send you a verification code via SMS</p>
            <form onSubmit={handleSendSMS}>
              <div className="input-group">
                <label htmlFor="phone">Phone Number</label>
                <input id="phone" type="tel" value={phoneNumber} onChange={(e) => setPhoneNumber(formatPhoneNumber(e.target.value))} placeholder="+1234567890" required disabled={loading} className="phone-input" />
              </div>
              <button type="submit" disabled={loading || !phoneNumber.trim()} className="primary-button">
                {loading ? <><span className="loading-spinner" /> Sending...</> : 'Send Code'}
              </button>
            </form>
            <div className="auth-divider"><span>or</span></div>
            <a href="/api/auth/coinpay/login" className="coinpay-button">
              <span className="coinpay-icon">🪙</span> Log in with CoinPay
            </a>
          </div>
        )}

        {step === 'verify' && (
          <div className="auth-step">
            <button className="back-button" onClick={() => setStep('phone')}>← Back</button>
            <h2>Enter verification code</h2>
            <p className="step-description">Code sent to <strong>{phoneNumber}</strong></p>
            <form onSubmit={handleVerifySMS}>
              <div className="input-group">
                <label htmlFor="code">Verification Code</label>
                <input id="code" type="text" value={verificationCode} onChange={handleCodeInput} placeholder="123456" maxLength={6} required disabled={loading} className="code-input" />
              </div>
              <button type="submit" disabled={loading || verificationCode.length !== 6} className="primary-button">
                {loading ? <><span className="loading-spinner" /> Verifying...</> : 'Verify'}
              </button>
            </form>
            <div className="resend-section">
              {canResend ? <button className="link-button" onClick={handleSendSMS}>Resend code</button> : <span className="countdown">Resend in {countdown}s</span>}
            </div>
          </div>
        )}

        {step === 'profile' && (
          <div className="auth-step">
            <button className="back-button" onClick={() => setStep('verify')}>← Back</button>
            <h2>Create your profile</h2>
            <p className="step-description">Choose a username to get started</p>
            <form onSubmit={completeProfile}>
              <div className="input-group">
                <label htmlFor="username">Username *</label>
                <input id="username" type="text" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="johndoe" required disabled={loading} pattern="[a-zA-Z0-9_]+" />
              </div>
              <div className="input-group">
                <label htmlFor="displayName">Display Name</label>
                <input id="displayName" type="text" value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="John Doe" disabled={loading} />
              </div>
              <button type="submit" disabled={loading || !username.trim()} className="primary-button">
                {loading ? <><span className="loading-spinner" /> Creating...</> : 'Create Account'}
              </button>
            </form>
          </div>
        )}

        {step === 'backup' && (
          <div className="auth-step">
            <h2>Set Your Backup PIN</h2>
            <p className="step-description">This PIN protects your encryption keys.</p>
            <div className="backup-warning"><p><strong>Important:</strong> Remember this PIN! Without it, you cannot restore your encryption keys.</p></div>
            <form onSubmit={setBackupPinFn}>
              <div className="input-group">
                <label>Backup PIN (6-12 digits) *</label>
                <div className="password-input">
                  <input type={showBackupPin ? 'text' : 'password'} inputMode="numeric" value={backupPin} onChange={(e) => setBackupPin(e.target.value.replace(/\D/g, '').slice(0, 12))} placeholder="Enter 6-12 digit PIN" required disabled={loading} className="code-input" />
                  <button type="button" className="toggle-password" onClick={() => setShowBackupPin(!showBackupPin)}>{showBackupPin ? '👁️' : '👁️‍🗨️'}</button>
                </div>
              </div>
              <div className="input-group">
                <label>Confirm PIN *</label>
                <div className="password-input">
                  <input type={showBackupPin ? 'text' : 'password'} inputMode="numeric" value={confirmBackupPin} onChange={(e) => setConfirmBackupPin(e.target.value.replace(/\D/g, '').slice(0, 12))} placeholder="Confirm your PIN" required disabled={loading} className="code-input" />
                </div>
              </div>
              <div className="button-group">
                <button type="submit" disabled={loading || !backupPin || !confirmBackupPin} className="primary-button">
                  {loading ? <><span className="loading-spinner" /> Setting PIN...</> : 'Set Backup PIN'}
                </button>
                <button type="button" className="secondary-button" onClick={() => { msgStore.warning('Backup PIN skipped. You can set one later in Settings.'); router.push('/chat'); }}>Skip (Not Recommended)</button>
              </div>
            </form>
          </div>
        )}

        {step === 'restore' && (
          <div className="auth-step">
            <h2>Restore Your Encryption Keys</h2>
            <p className="step-description">Enter your Backup PIN to restore your encryption keys on this device.</p>
            <form onSubmit={restoreWithPin}>
              <div className="input-group">
                <label>Backup PIN *</label>
                <div className="password-input">
                  <input type={showRestorePin ? 'text' : 'password'} inputMode="numeric" value={restorePin} onChange={(e) => setRestorePin(e.target.value.replace(/\D/g, '').slice(0, 12))} placeholder="Enter your PIN" required disabled={isRestoring} className="code-input" />
                  <button type="button" className="toggle-password" onClick={() => setShowRestorePin(!showRestorePin)}>{showRestorePin ? '👁️' : '👁️‍🗨️'}</button>
                </div>
              </div>
              <div className="button-group">
                <button type="submit" disabled={isRestoring || !restorePin} className="primary-button">
                  {isRestoring ? <><span className="loading-spinner" /> Restoring...</> : 'Restore Keys'}
                </button>
                <button type="button" className="secondary-button" onClick={() => { msgStore.warning('Key restore skipped.'); router.push('/chat'); }}>Skip</button>
              </div>
            </form>
          </div>
        )}

        <div className="auth-footer">
          <p className="privacy-note">Your data is encrypted end-to-end. We cannot read your messages.</p>
        </div>
      </div>

      <style>{`
        .auth-container { min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 1rem; background: linear-gradient(135deg, var(--color-bg-secondary) 0%, var(--color-bg-tertiary) 100%); }
        .auth-card { background: var(--color-bg-primary); border-radius: 1rem; padding: 2rem; width: 100%; max-width: 400px; box-shadow: var(--shadow-lg); border: 1px solid var(--color-border-primary); }
        .auth-header { text-align: center; margin-bottom: 2rem; }
        .logo { display: flex; align-items: center; justify-content: center; gap: .5rem; margin-bottom: .5rem; }
        .logo-icon { font-size: 2rem; }
        .logo h1 { font-size: 1.5rem; font-weight: 700; color: var(--color-brand-primary); margin: 0; }
        .subtitle { color: var(--color-text-secondary); margin: 0; }
        .auth-step h2 { font-size: 1.25rem; font-weight: 600; margin-bottom: .5rem; color: var(--color-text-primary); }
        .step-description { color: var(--color-text-secondary); margin-bottom: 1.5rem; line-height: 1.5; }
        .input-group { margin-bottom: 1rem; }
        .input-group label { display: block; font-weight: 500; margin-bottom: .5rem; color: var(--color-text-primary); }
        .input-group input { width: 100%; padding: .75rem; border: 1px solid var(--color-border-primary); border-radius: .5rem; font-size: 1rem; background: var(--color-bg-primary); color: var(--color-text-primary); }
        .input-group input:focus { outline: none; border-color: var(--color-brand-primary); box-shadow: 0 0 0 3px rgb(99 102 241 / .1); }
        .phone-input, .code-input { font-family: monospace; letter-spacing: .05em; }
        .code-input { font-size: 1.25rem; text-align: center; letter-spacing: .25em; }
        .primary-button { width: 100%; padding: .75rem; background: var(--color-brand-primary); color: white; border: none; border-radius: .5rem; font-size: 1rem; font-weight: 500; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: .5rem; }
        .primary-button:hover:not(:disabled) { background: var(--color-brand-secondary); }
        .primary-button:disabled { opacity: .6; cursor: not-allowed; }
        .secondary-button { width: 100%; padding: .75rem; background: var(--color-bg-secondary); color: var(--color-text-secondary); border: 1px solid var(--color-border-primary); border-radius: .5rem; font-size: .875rem; font-weight: 500; cursor: pointer; }
        .secondary-button:hover:not(:disabled) { background: var(--color-bg-tertiary); }
        .back-button, .link-button { background: none; border: none; color: var(--color-brand-primary); cursor: pointer; font-size: .875rem; padding: 0; }
        .back-button { margin-bottom: 1rem; display: block; }
        .link-button { text-decoration: underline; }
        .resend-section { text-align: center; margin-top: 1rem; }
        .countdown { color: var(--color-text-secondary); font-size: .875rem; }
        .messages-container { margin-bottom: 1rem; }
        .loading-spinner { width: 1rem; height: 1rem; border: 2px solid transparent; border-top: 2px solid currentColor; border-radius: 50%; animation: spin 1s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }
        .auth-footer { margin-top: 2rem; text-align: center; }
        .privacy-note { font-size: .75rem; color: var(--color-text-secondary); }
        .backup-warning { background: rgba(239,68,68,.1); border: 1px solid #ef4444; border-radius: .375rem; padding: 1rem; margin: 1rem 0; }
        .backup-warning p { color: #dc2626; margin: 0; font-weight: 500; font-size: .875rem; }
        .button-group { display: flex; flex-direction: column; gap: .75rem; margin-top: 1.5rem; }
        .password-input { position: relative; display: flex; align-items: center; }
        .password-input input { padding-right: 3rem; }
        .toggle-password { position: absolute; right: .75rem; background: none; border: none; cursor: pointer; font-size: 1rem; }
        .auth-divider { display: flex; align-items: center; text-align: center; margin: 1.25rem 0; color: var(--color-text-secondary); font-size: .75rem; }
        .auth-divider::before, .auth-divider::after { content: ''; flex: 1; border-bottom: 1px solid var(--color-border-primary); }
        .auth-divider span { padding: 0 .75rem; }
        .coinpay-button { width: 100%; box-sizing: border-box; padding: .75rem; background: var(--color-bg-secondary); color: var(--color-text-primary); border: 1px solid var(--color-border-primary); border-radius: .5rem; font-size: 1rem; font-weight: 500; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: .5rem; text-decoration: none; }
        .coinpay-button:hover { background: var(--color-bg-tertiary); }
        .coinpay-icon { font-size: 1.1rem; }
      `}</style>
    </div>
  );
}

// src/routes/auth/+page.svelte
<script>
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { browser } from '$app/environment';
	import { auth, isAuthenticated, isLoading } from '$lib/stores/auth.js';
	import { messages } from '$lib/stores/messages.js';
	import { t } from '$lib/stores/i18n.js';
	import { createSupabaseClient } from '$lib/supabase.js';
	import { currentTheme, themeUtils } from '$lib/stores/theme.js';
	import Message from '$lib/components/Message.svelte';
	import AvatarUpload from '$lib/components/AvatarUpload.svelte';
	import { keyManager } from '$lib/crypto/key-manager.js';
	import { privateKeyManager } from '$lib/crypto/private-key-manager.js';
	import { indexedDBManager } from '$lib/crypto/indexed-db-manager.js';
	/** @type {'phone' | 'verify' | 'profile' | 'backup' | 'restore'} */
	let step = $state('phone');
	let phoneNumber = $state('');
	let verificationCode = $state('');
	let username = $state('');
	let displayName = $state('');
	let isNewUser = $state(false);
	let countdown = $state(0);
	let canResend = $state(true);
	let expiresAt = $state(/** @type {string | null} */ (null));
	/** @type {any} */
	let verifiedSession = $state(null); // Store the verified session for account creation
	/** @type {string | null | undefined} */
	let avatarUrl = $state(null); // Store uploaded avatar URL
	let avatarFile = null; //stores selected file
	/** @type {string | null | undefined} */
	let createdUserId = $state(null); // Store user ID after account creation for avatar upload

	// Backup PIN
	let backupPin = $state('');
	let confirmBackupPin = $state('');
	let showBackupPin = $state(false);

	// Restore PIN (for existing user login)
	let restorePin = $state('');
	let showRestorePin = $state(false);
	let isRestoring = $state(false);

	// Redirect if already authenticated
	onMount(() => {
		if ($isAuthenticated) {
			goto('/chat');
		}

		// Ensure theme is applied
		if (browser) {
			themeUtils.applyTheme($currentTheme);
		}
	});

	/**
	 * Format phone number as user types
	 * @param {string} value
	 */
	function formatPhoneNumber(value) {
		// Remove all non-digits except the leading +
		const cleanValue = value.replace(/[^\d+]/g, '');

		// If it starts with digits (no +), add the + prefix
		if (cleanValue.length > 0 && !cleanValue.startsWith('+')) {
			return '+' + cleanValue;
		}

		return cleanValue;
	}

	/**
	 * Handle phone number input
	 * @param {Event} event
	 */
	function handlePhoneInput(event) {
		const input = /** @type {HTMLInputElement} */ (event.target);
		phoneNumber = formatPhoneNumber(input.value);
	}

	/**
	 * Start countdown timer
	 * @param {number} seconds
	 */
	function startCountdown(seconds) {
		countdown = seconds;
		canResend = false;

		const timer = setInterval(() => {
			countdown--;
			if (countdown <= 0) {
				clearInterval(timer);
				canResend = true;
			}
		}, 1000);
	}

	/**
	 * Send SMS verification code
	 */
	async function sendSMS() {
		if (!phoneNumber.trim()) {
			return;
		}

		const result = await auth.sendSMS(phoneNumber);

		if (result.success) {
			step = 'verify';
			// Supabase OTP expires in 300 seconds (5 minutes) as configured
			expiresAt = new Date(Date.now() + 300 * 1000).toISOString();
			startCountdown(60); // 60 second cooldown for resend (not expiration)
		}
	}

	/**
	 * Verify SMS code
	 */
	async function verifySMS() {
		if (!verificationCode.trim() || verificationCode.length !== 6) {
			return;
		}

		// For initial verification, don't send username/displayName
		// These are only needed for new user profile completion
		const result = await auth.verifySMS(phoneNumber, verificationCode);

		if (result.success) {
			if (result.isNewUser) {
				// New user - show success and redirect
				goto('/chat?welcome=true');
			} else {
				// Existing user - check key state
				try {
					const hasLocalKeys = await indexedDBManager.get('qryptchat_pq_keypair');
					const hasBackup = await privateKeyManager.hasServerBackup();
					const pinCheckRes = await fetch('/api/auth/backup-pin');
					const pinData = pinCheckRes.ok ? await pinCheckRes.json() : { hasPin: false };

					if (hasBackup && !hasLocalKeys) {
						// Keys on server but not locally - need to restore
						step = 'restore';
						return;
					}

					if (!pinData.hasPin && hasLocalKeys) {
						// Has local keys but no backup PIN set - prompt to set one
						step = 'backup';
						return;
					}
				} catch (err) {
					console.warn('Key check failed:', err);
				}
				// Everything set up - proceed normally
				goto('/chat');
			}
		} else if (result.requiresUsername) {
			// New user needs to provide username - store session for account creation
			verifiedSession = result.session;
			isNewUser = true;
			step = 'profile';
		}
	}

	/**
	 * Complete profile setup for new users
	 */

	/**
	 * Go back to previous step
	 */
	function goBack() {
		if (step === 'verify') {
			step = 'phone';
		} else if (step === 'profile') {
			step = 'verify';
		}
	}

	/**
	 * Handle verification code input (auto-advance)
	 * @param {Event} event
	 */
	function handleCodeInput(event) {
		const input = /** @type {HTMLInputElement} */ (event.target);
		verificationCode = input.value.replace(/\D/g, '').slice(0, 6);

		// Auto-verify when 6 digits entered
		if (verificationCode.length === 6) {
			setTimeout(verifySMS, 100);
		}
	}

	/**
	 * Handle avatar upload success
	 * @param {CustomEvent} event
	 * changed to store file obj directly instead of blob url
	 */
	function handleAvatarUploaded(event) {
		avatarFile = event.detail.file;
		avatarUrl = event.detail.avatarUrl;

		//if user already created, upload immediately
		if (createdUserId && verifiedSession?.access_token) {
			uploadAvatarFile(avatarFile);
		} else {
			console.log('📸 Avatar preview ready for upload after user creation');
		}
	}

	/*
	 * upload avatar file to backend
	 * new fxn added
	 */

	async function uploadAvatarFile(file) {
		try {
			const formData = new FormData();
			formData.append('avatar', file);
			// Upload avatar using the dedicated endpoint
			const uploadResponse = await fetch('/api/auth/upload-avatar', {
				method: 'POST',
				headers: {
					Authorization: `Bearer ${verifiedSession.access_token}`
				},
				body: formData
			});

			const uploadResult = await uploadResponse.json();

			console.log(uploadResult);

			if (uploadResponse.ok && uploadResult.avatarUrl) {
				// Clean up blob URL
				URL.revokeObjectURL(avatarUrl);
				avatarUrl = uploadResult.avatarUrl;
				console.log('📸 ✅ Avatar uploaded successfully after user creation');
			} else {
				console.warn('Avatar upload failed:', uploadResult.error);
				messages.warning('Account created but avatar upload failed. You can add one later.');
			}
		} catch (avatarError) {
			console.error('Avatar upload error:', avatarError);
			messages.warning('Account created but avatar upload failed. You can add one later.');
		}
	}

	/**
	 * Handle avatar upload error
	 * @param {CustomEvent} event
	 */
	function handleAvatarError(event) {
		messages.error(event.detail.message || 'Failed to upload profile picture');
	}

	/**
	 * Handle avatar removal
	 */
	function handleAvatarRemoved() {
		avatarUrl = null;
		avatarFile = null;
		messages.info('Profile picture removed');
	}

	async function completeProfile() {
		if (!username.trim()) {
			return;
		}

		// Use the verified session JWT token to create account
		// Call the verify-sms endpoint with the session token instead of OTP
		if (!verifiedSession?.access_token) {
			messages.error('Session expired. Please verify your phone number again.');
			step = 'verify';
			return;
		}

		try {
			// Create user account first (without avatar)
			const body = JSON.stringify({
				phoneNumber,
				username,
				displayName: displayName || username,
				useSession: true // Flag to indicate we're using session auth
			});

			const headers = {
				Authorization: `Bearer ${verifiedSession.access_token}`,
				'Content-Type': 'application/json'
			};

			const apiResponse = await fetch('/api/auth/verify-sms', {
				method: 'POST',
				headers,
				body
			});

			const data = await apiResponse.json();

			if (apiResponse.ok && data.success) {
				// Store user data and session
				if (browser) {
					localStorage.setItem('qrypt_user', JSON.stringify(data.user));
					localStorage.setItem('supabase.auth.token', JSON.stringify(verifiedSession));
				}

				// Set the session in the Supabase client
				const supabase = createSupabaseClient();
				await supabase.auth.setSession(verifiedSession);

				// Upload avatar after user creation if one was selected
				if (avatarFile) {
					//using file directly
					await uploadAvatarFile(avatarFile);
				}

				// Generate encryption keys for new user
				try {
					await keyManager.generateUserKeys();
					console.log('🔑 Generated encryption keys for new user');

					// Go to backup step (set PIN)
					step = 'backup';
					messages.success('Account created! Please set a Backup PIN to protect your encryption keys.');
				} catch (keyError) {
					console.error('Failed to generate encryption keys:', keyError);
					messages.warning(
						'Account created but failed to generate encryption keys. You can generate them later in Settings.'
					);
					goto('/chat?welcome=true');
				}
			} else {
				messages.error(data.error || 'Failed to create account');
			}
		} catch (error) {
			console.error('Profile completion error:', error);
			messages.error('Failed to create account. Please try again.');
		}
	}

	/**
	 * Set backup PIN and encrypt keys to server during registration
	 */
	async function setBackupPin() {
		if (!backupPin || backupPin.trim().length === 0) {
			messages.error('Please enter a Backup PIN');
			return;
		}

		if (!/^\d+$/.test(backupPin)) {
			messages.error('PIN must contain only digits');
			return;
		}

		if (backupPin.length !== 6) {
			messages.error('PIN must be exactly 6 digits');
			return;
		}

		if (backupPin !== confirmBackupPin) {
			messages.error('PINs do not match');
			return;
		}

		try {
			// Store the PIN hash on the server
			const headers = /** @type {Record<string, string>} */ ({
				'Content-Type': 'application/json'
			});
			if (verifiedSession?.access_token) {
				headers['Authorization'] = `Bearer ${verifiedSession.access_token}`;
			}

			const pinResponse = await fetch('/api/auth/backup-pin', {
				method: 'POST',
				headers,
				body: JSON.stringify({ pin: backupPin })
			});

			if (!pinResponse.ok) {
				const err = await pinResponse.json().catch(() => ({}));
				throw new Error(err.error || 'Failed to save PIN');
			}

			// Backup keys to server encrypted with the PIN
			await privateKeyManager.backupKeysToServer(backupPin);

			messages.success('Backup PIN set and keys backed up! Welcome to QryptChat!');
			backupPin = '';
			confirmBackupPin = '';
			goto('/chat?welcome=true');
		} catch (error) {
			console.error('Failed to set backup PIN:', error);
			const errorMessage = error instanceof Error ? error.message : 'Unknown error';
			messages.error('Failed to set backup PIN: ' + errorMessage);
		}
	}

	/**
	 * Skip backup PIN (not recommended but allowed)
	 */
	function skipBackupPin() {
		messages.warning('Backup PIN skipped. You can set one later in Settings.');
		goto('/chat?welcome=true');
	}

	let restoreAttempts = $state(0);
	const MAX_RESTORE_ATTEMPTS = 5;

	/**
	 * Restore keys from server using the backup PIN (existing user login)
	 */
	async function restoreWithPin() {
		if (!restorePin || restorePin.trim().length === 0) {
			messages.error('Please enter your Backup PIN');
			return;
		}

		if (restoreAttempts >= MAX_RESTORE_ATTEMPTS) {
			messages.error('Too many failed attempts. Please try again later.');
			return;
		}

		isRestoring = true;
		try {
			await privateKeyManager.restoreKeysFromServer(restorePin);
			messages.success('Encryption keys restored successfully!');
			restorePin = '';
			restoreAttempts = 0;
			goto('/chat');
		} catch (error) {
			restoreAttempts++;
			const remaining = MAX_RESTORE_ATTEMPTS - restoreAttempts;
			console.error('Failed to restore keys:', error);
			if (remaining <= 0) {
				messages.error('Too many failed attempts. Please try again later.');
			} else {
				messages.error(`Wrong PIN. ${remaining} attempt${remaining === 1 ? '' : 's'} remaining.`);
			}
			restorePin = '';
		} finally {
			isRestoring = false;
		}
	}

	/**
	 * Skip key restore and proceed without keys
	 */
	function skipRestore() {
		messages.warning('Key restore skipped. You can restore your keys later in Settings.');
		goto('/chat');
	}

	onMount(() => {
		// Focus first input
		const firstInput = document.querySelector('input');
		if (firstInput) {
			firstInput.focus();
		}
	});
</script>

<svelte:head>
	<title>{$t('auth.title')} - QryptChat</title>
</svelte:head>

<div class="auth-container">
	<div class="auth-card">
		<!-- Header -->
		<div class="auth-header">
			<div class="logo">
				<div class="logo-icon">🔐</div>
				<h1>QryptChat</h1>
			</div>
			<p class="subtitle">{$t('auth.subtitle')}</p>
		</div>

		<!-- Messages -->
		<div class="messages-container">
			{#each $messages as message (message.id)}
				<Message
					type={message.type}
					message={message.message}
					title={message.title}
					dismissible={message.dismissible}
					autoDismiss={message.autoDismiss}
					on:dismiss={() => messages.remove(message.id)}
				/>
			{/each}
		</div>

		<!-- Phone Number Step -->
		{#if step === 'phone'}
			<div class="auth-step">
				<h2>{$t('auth.enterPhone')}</h2>
				<p class="step-description">{$t('auth.phoneDescription')}</p>

				<form onsubmit={sendSMS}>
					<div class="input-group">
						<label for="phone">{$t('auth.phoneNumber')}</label>
						<input
							id="phone"
							type="tel"
							bind:value={phoneNumber}
							oninput={handlePhoneInput}
							placeholder="+1234567890"
							required
							disabled={$isLoading}
							class="phone-input"
						/>
					</div>

					<button type="submit" disabled={$isLoading || !phoneNumber.trim()} class="primary-button">
						{#if $isLoading}
							<span class="loading-spinner"></span>
							{$t('auth.sending')}
						{:else}
							{$t('auth.sendCode')}
						{/if}
					</button>
				</form>
			</div>
		{/if}

		<!-- Verification Step -->
		{#if step === 'verify'}
			<div class="auth-step">
				<button class="back-button" onclick={goBack}>
					← {$t('common.back')}
				</button>

				<h2>{$t('auth.enterCode')}</h2>
				<p class="step-description">
					{$t('auth.codeDescription')} <strong>{phoneNumber}</strong>
				</p>

				<form onsubmit={verifySMS}>
					<div class="input-group">
						<label for="code">{$t('auth.verificationCode')}</label>
						<input
							id="code"
							type="text"
							bind:value={verificationCode}
							oninput={handleCodeInput}
							placeholder="123456"
							maxlength="6"
							required
							disabled={$isLoading}
							class="code-input"
						/>
					</div>

					<button
						type="submit"
						disabled={$isLoading || verificationCode.length !== 6}
						class="primary-button"
					>
						{#if $isLoading}
							<span class="loading-spinner"></span>
							{$t('auth.verifying')}
						{:else}
							{$t('auth.verify')}
						{/if}
					</button>
				</form>

				<div class="resend-section">
					{#if canResend}
						<button class="link-button" onclick={sendSMS}>
							{$t('auth.resendCode')}
						</button>
					{:else}
						<span class="countdown">
							{$t('auth.resendIn')}
							{countdown}s
						</span>
					{/if}
				</div>
			</div>
		{/if}

		<!-- Profile Setup Step -->
		{#if step === 'profile'}
			<div class="auth-step">
				<button class="back-button" onclick={goBack}>
					← {$t('common.back')}
				</button>

				<h2>{$t('auth.createProfile')}</h2>
				<p class="step-description">{$t('auth.profileDescription')}</p>

				<form onsubmit={completeProfile}>
					<!-- Avatar Upload Section -->
					<div class="avatar-section">
						<div class="avatar-label">Profile Picture (Optional)</div>
						<div class="avatar-upload-container">
							<AvatarUpload
								userId={null}
								currentAvatarUrl={avatarUrl ? null : undefined}
								size="medium"
								disabled={$isLoading}
								previewOnly={true}
								on:uploaded={handleAvatarUploaded}
								on:error={handleAvatarError}
								on:removed={handleAvatarRemoved}
							/>
						</div>
						<p class="avatar-description">
							Add a profile picture to help others recognize you. You can skip this step and add one
							later.
						</p>
					</div>

					<div class="input-group">
						<label for="username">{$t('auth.username')} *</label>
						<input
							id="username"
							type="text"
							bind:value={username}
							placeholder="johndoe"
							required
							disabled={$isLoading}
							pattern="[a-zA-Z0-9_]+"
							title="Username can only contain letters, numbers, and underscores"
						/>
					</div>

					<div class="input-group">
						<label for="displayName">{$t('auth.displayName')}</label>
						<input
							id="displayName"
							type="text"
							bind:value={displayName}
							placeholder="John Doe"
							disabled={$isLoading}
						/>
					</div>

					<button type="submit" disabled={$isLoading || !username.trim()} class="primary-button">
						{#if $isLoading}
							<span class="loading-spinner"></span>
							{$t('auth.creating')}
						{:else}
							{$t('auth.createAccount')}
						{/if}
					</button>
				</form>
			</div>
		{/if}

		<!-- Backup PIN Step (Registration) -->
		{#if step === 'backup'}
			<div class="auth-step">
				<h2>Set Your Backup PIN</h2>
				<p class="step-description">
					This PIN protects your encryption keys. You will need it to restore your keys on a new device.
				</p>

				<div class="backup-warning">
					<p>
						<strong>Important:</strong> Remember this PIN! Without it, you cannot restore your encryption
						keys if you lose this device or clear your browser data.
					</p>
				</div>

				<form onsubmit={setBackupPin}>
					<div class="input-group">
						<label for="backup-pin">Backup PIN (6-digits) *</label>
						<div class="password-input">
							<input
								id="backup-pin"
								type={showBackupPin ? 'text' : 'password'}
								inputmode="numeric"
								pattern="[0-9]*"
								bind:value={backupPin}
								maxlength="6"
								oninput={(e) => { backupPin = e.target.value.replace(/\D/g, '').slice(0, 6); }}
								placeholder="Enter your 6-digit PIN"
								required
								disabled={$isLoading}
								class="code-input"
							/>
							<button
								type="button"
								class="toggle-password"
								onclick={() => (showBackupPin = !showBackupPin)}
								disabled={$isLoading}
							>
								{showBackupPin ? '👁️' : '👁️‍🗨️'}
							</button>
						</div>
					</div>

					<div class="input-group">
						<label for="confirm-backup-pin">Confirm PIN *</label>
						<div class="password-input">
							<input
								id="confirm-backup-pin"
								type={showBackupPin ? 'text' : 'password'}
								inputmode="numeric"
								pattern="[0-9]*"
								bind:value={confirmBackupPin}
								maxlength="6"
								oninput={(e) => { confirmBackupPin = e.target.value.replace(/\D/g, '').slice(0, 6); }}
								placeholder="Confirm your PIN"
								required
								disabled={$isLoading}
								class="code-input"
							/>
							<button
								type="button"
								class="toggle-password"
								onclick={() => (showBackupPin = !showBackupPin)}
								disabled={$isLoading}
							>
								{showBackupPin ? '👁️' : '👁️‍🗨️'}
							</button>
						</div>
					</div>

					<div class="button-group">
						<button
							type="submit"
							disabled={$isLoading || !backupPin || !confirmBackupPin}
							class="primary-button"
						>
							{#if $isLoading}
								<span class="loading-spinner"></span>
								Setting PIN...
							{:else}
								Set Backup PIN
							{/if}
						</button>

						<button
							type="button"
							class="secondary-button"
							onclick={skipBackupPin}
							disabled={$isLoading}
						>
							Skip (Not Recommended)
						</button>
					</div>
				</form>

				<div class="backup-info">
					<p><strong>About your Backup PIN:</strong></p>
					<ul>
						<li>Use a PIN you can remember (like a wallet passphrase)</li>
						<li>It encrypts your keys before uploading to the server</li>
						<li>On a new device, enter this PIN to restore your keys</li>
						<li>This is NOT your SMS verification code</li>
					</ul>
				</div>
			</div>
		{/if}

		<!-- Restore Keys Step (Existing User Login) -->
		{#if step === 'restore'}
			<div class="auth-step">
				<h2>Restore Your Encryption Keys</h2>
				<p class="step-description">
					A key backup was found on the server. Enter your Backup PIN to restore your encryption keys on this device.
				</p>

				<form onsubmit={restoreWithPin}>
					<div class="input-group">
						<label for="restore-pin">Backup PIN *</label>
						<div class="password-input">
							<input
								id="restore-pin"
								type={showRestorePin ? 'text' : 'password'}
								inputmode="numeric"
								pattern="[0-9]*"
								bind:value={restorePin}
								maxlength="6"
								oninput={(e) => { restorePin = e.target.value.replace(/\D/g, '').slice(0, 6); }}
								placeholder="Enter your 6-digit PIN"
								required
								disabled={isRestoring}
								class="code-input"
							/>
							<button
								type="button"
								class="toggle-password"
								onclick={() => (showRestorePin = !showRestorePin)}
								disabled={isRestoring}
							>
								{showRestorePin ? '👁️' : '👁️‍🗨️'}
							</button>
						</div>
					</div>

					<div class="button-group">
						<button
							type="submit"
							disabled={isRestoring || !restorePin}
							class="primary-button"
						>
							{#if isRestoring}
								<span class="loading-spinner"></span>
								Restoring Keys...
							{:else}
								Restore Keys
							{/if}
						</button>

						<button
							type="button"
							class="secondary-button"
							onclick={skipRestore}
							disabled={isRestoring}
						>
							Skip
						</button>
					</div>
				</form>
			</div>
		{/if}

		<!-- Footer -->
		<div class="auth-footer">
			<p class="privacy-note">
				{$t('auth.privacyNote')}
			</p>
		</div>
	</div>
</div>

<style>
	.auth-container {
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 1rem;
		background: linear-gradient(
			135deg,
			var(--color-bg-secondary) 0%,
			var(--color-bg-tertiary) 100%
		);
	}

	.auth-card {
		background: var(--color-bg-primary);
		border-radius: 1rem;
		padding: 2rem;
		width: 100%;
		max-width: 400px;
		box-shadow: var(--shadow-lg);
		border: 1px solid var(--color-border-primary);
	}

	.auth-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.logo {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		margin-bottom: 0.5rem;
	}

	.logo-icon {
		font-size: 2rem;
	}

	.logo h1 {
		font-size: 1.5rem;
		font-weight: 700;
		color: var(--color-brand-primary);
		margin: 0;
	}

	.subtitle {
		color: var(--color-text-secondary);
		margin: 0;
	}

	.auth-step h2 {
		font-size: 1.25rem;
		font-weight: 600;
		margin-bottom: 0.5rem;
		color: var(--color-text-primary);
	}

	.step-description {
		color: var(--color-text-secondary);
		margin-bottom: 1.5rem;
		line-height: 1.5;
	}

	.input-group {
		margin-bottom: 1rem;
	}

	.input-group label {
		display: block;
		font-weight: 500;
		margin-bottom: 0.5rem;
		color: var(--color-text-primary);
	}

	.input-group input {
		width: 100%;
		padding: 0.75rem;
		border: 1px solid var(--color-border-primary);
		border-radius: 0.5rem;
		font-size: 1rem;
		transition: border-color 0.2s ease;
		background: var(--color-bg-primary);
		color: var(--color-text-primary);
	}

	.input-group input:focus {
		outline: none;
		border-color: var(--color-brand-primary);
		box-shadow: 0 0 0 3px rgb(99 102 241 / 0.1);
	}

	.input-group input:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.phone-input {
		font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', monospace;
		letter-spacing: 0.05em;
	}

	.code-input {
		font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', monospace;
		font-size: 1.25rem;
		text-align: center;
		letter-spacing: 0.25em;
	}

	.primary-button {
		width: 100%;
		padding: 0.75rem;
		background: var(--color-brand-primary);
		color: white;
		border: none;
		border-radius: 0.5rem;
		font-size: 1rem;
		font-weight: 500;
		cursor: pointer;
		transition: background-color 0.2s ease;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
	}

	.primary-button:hover:not(:disabled) {
		background: var(--color-brand-secondary);
	}

	.primary-button:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.back-button {
		background: none;
		border: none;
		color: var(--color-brand-primary);
		cursor: pointer;
		font-size: 0.875rem;
		margin-bottom: 1rem;
		padding: 0.25rem 0;
	}

	.back-button:hover {
		color: var(--color-brand-secondary);
	}

	.link-button {
		background: none;
		border: none;
		color: var(--color-brand-primary);
		cursor: pointer;
		text-decoration: underline;
		font-size: 0.875rem;
	}

	.link-button:hover {
		color: var(--color-brand-secondary);
	}

	.resend-section {
		text-align: center;
		margin-top: 1rem;
	}

	.countdown {
		color: var(--color-text-secondary);
		font-size: 0.875rem;
	}

	.messages-container {
		margin-bottom: 1rem;
	}

	.loading-spinner {
		width: 1rem;
		height: 1rem;
		border: 2px solid transparent;
		border-top: 2px solid currentColor;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	.auth-footer {
		margin-top: 2rem;
		text-align: center;
	}

	.privacy-note {
		font-size: 0.75rem;
		color: var(--color-text-secondary);
		line-height: 1.4;
		margin: 0;
	}

	/* Avatar Upload Styles */
	.avatar-section {
		margin-bottom: 1.5rem;
		text-align: center;
	}

	.avatar-label {
		display: block;
		font-weight: 500;
		margin-bottom: 0.75rem;
		color: var(--color-text-primary);
		font-size: 0.875rem;
	}

	.avatar-upload-container {
		display: flex;
		justify-content: center;
		margin-bottom: 0.5rem;
	}

	.avatar-description {
		font-size: 0.75rem;
		color: var(--color-text-secondary);
		line-height: 1.4;
		margin: 0;
		max-width: 280px;
		margin-left: auto;
		margin-right: auto;
	}

	@media (max-width: 480px) {
		.auth-card {
			padding: 1.5rem;
		}

		.logo h1 {
			font-size: 1.25rem;
		}

		.avatar-description {
			font-size: 0.7rem;
		}
	}

	/* Password input styles */
	.password-input {
		position: relative;
		display: flex;
		align-items: center;
	}

	.password-input input {
		padding-right: 3rem;
	}

	.toggle-password {
		position: absolute;
		right: 0.75rem;
		background: none;
		border: none;
		cursor: pointer;
		font-size: 1rem;
		color: var(--color-text-secondary);
		padding: 0.25rem;
	}

	.toggle-password:hover {
		color: var(--color-text-primary);
	}

	/* Backup step specific styles */
	.backup-warning {
		background: rgba(239, 68, 68, 0.1);
		border: 1px solid #ef4444;
		border-radius: 0.375rem;
		padding: 1rem;
		margin: 1rem 0;
	}

	.backup-warning p {
		color: #dc2626;
		margin: 0;
		font-weight: 500;
		font-size: 0.875rem;
	}

	.button-group {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
		margin-top: 1.5rem;
	}

	.secondary-button {
		width: 100%;
		padding: 0.75rem;
		background: var(--color-bg-secondary);
		color: var(--color-text-secondary);
		border: 1px solid var(--color-border-primary);
		border-radius: 0.5rem;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.secondary-button:hover:not(:disabled) {
		background: var(--color-bg-tertiary);
		border-color: var(--color-border-secondary);
	}

	.secondary-button:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.backup-info {
		margin-top: 1.5rem;
		padding: 1rem;
		background: rgba(34, 197, 94, 0.05);
		border-radius: 0.375rem;
		border: 1px solid rgba(34, 197, 94, 0.2);
	}

	.backup-info p {
		color: #065f46;
		margin: 0 0 0.5rem 0;
		font-weight: 600;
		font-size: 0.875rem;
	}

	.backup-info ul {
		margin: 0;
		padding-left: 1.25rem;
		font-size: 0.8125rem;
		color: #047857;
		line-height: 1.5;
	}

	.backup-info li {
		margin-bottom: 0.25rem;
	}

	.backup-info li:last-child {
		margin-bottom: 0;
	}
</style>
