// src/lib/components/chat/TypingIndicator.svelte
<script>
	let { users = [] } = $props();

	const typingText = $derived(() => {
		if (users.length === 0) return '';
		if (users.length === 1) return `${users[0].display_name || users[0].username} is typing...`;
		if (users.length === 2) return `${users[0].display_name || users[0].username} and ${users[1].display_name || users[1].username} are typing...`;
		return `${users.length} people are typing...`;
	});
</script>

{#if users.length > 0}
	<div class="typing-indicator">
		<div class="typing-avatar">
			<div class="typing-dots">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</div>
		<div class="typing-text">
			{typingText}
		</div>
	</div>
{/if}

<style>
	.typing-indicator {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 0.5rem 0;
		margin-bottom: 0.5rem;
		opacity: 0.8;
	}

	.typing-avatar {
		width: 32px;
		height: 32px;
		border-radius: 50%;
		background: var(--color-surface);
		border: 1px solid var(--color-border);
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
	}

	.typing-dots {
		display: flex;
		gap: 2px;
	}

	.typing-dots span {
		width: 4px;
		height: 4px;
		border-radius: 50%;
		background: var(--color-text-secondary);
		animation: typing-bounce 1.4s infinite ease-in-out;
	}

	.typing-dots span:nth-child(1) {
		animation-delay: -0.32s;
	}

	.typing-dots span:nth-child(2) {
		animation-delay: -0.16s;
	}

	.typing-text {
		font-size: 0.875rem;
		color: var(--color-text-secondary);
		font-style: italic;
	}

	@keyframes typing-bounce {
		0%, 80%, 100% {
			transform: scale(0.8);
			opacity: 0.5;
		}
		40% {
			transform: scale(1);
			opacity: 1;
		}
	}
</style>

// src/lib/components/chat/TypingIndicator.jsx
'use client';

export default function TypingIndicator({ typingUsers = [] }) {
  if (typingUsers.length === 0) return null;

  const names = typingUsers.map((u) => u.display_name || u.username || 'Someone');
  const text = names.length === 1
    ? `${names[0]} is typing...`
    : names.length === 2
    ? `${names[0]} and ${names[1]} are typing...`
    : `${names.slice(0, 2).join(', ')} and others are typing...`;

  return (
    <div className="typing-indicator">
      <div className="typing-dots">
        <span /><span /><span />
      </div>
      <span className="typing-text">{text}</span>
      <style>{`
        .typing-indicator { display: flex; align-items: center; gap: .5rem; padding: .5rem 1rem; color: var(--color-text-secondary); font-size: .875rem; font-style: italic; }
        .typing-dots { display: flex; gap: 3px; }
        .typing-dots span { width: 6px; height: 6px; background: var(--color-text-secondary); border-radius: 50%; animation: bounce 1.2s infinite; }
        .typing-dots span:nth-child(2) { animation-delay: .2s; }
        .typing-dots span:nth-child(3) { animation-delay: .4s; }
        @keyframes bounce { 0%, 60%, 100% { transform: translateY(0); } 30% { transform: translateY(-8px); } }
      `}</style>
    </div>
  );
}
