// src/app/admin/page.jsx
import { notFound, redirect } from 'next/navigation';
import Link from 'next/link';
import { createSupabaseServerClient } from '@/lib/supabase';
import { getServiceRoleClient } from '@/lib/supabase/service-role';

export const metadata = {
  title: 'Admin — QryptChat',
  robots: { index: false, follow: false },
};

export const dynamic = 'force-dynamic';

export default async function AdminPage() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/auth');

  const svc = getServiceRoleClient();
  const { data: adminRow } = await svc
    .from('admin_users')
    .select('user_id')
    .eq('user_id', user.id)
    .maybeSingle();
  if (!adminRow) notFound();

  const [{ data: integrations }, { data: posts }] = await Promise.all([
    svc.from('autoblog_integrations')
      .select('id, name, kind, request_count, last_used_at, created_at')
      .order('created_at', { ascending: false }),
    svc.from('blog_posts')
      .select('id, slug, title, source, published_at')
      .order('published_at', { ascending: false })
      .limit(20),
  ]);

  const cardStyle = { border: '1px solid var(--color-border)', borderRadius: '0.5rem', padding: '1.25rem' };
  const mutedColor = 'var(--color-text-secondary)';

  return (
    <div className="container" style={{ padding: '3rem 0', maxWidth: '48rem', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <div>
        <h1 style={{ fontSize: '2rem', fontWeight: 700, margin: 0 }}>Admin</h1>
        <p style={{ marginTop: '0.25rem', fontSize: '0.875rem', color: mutedColor }}>
          Logged in as {user.email}
        </p>
      </div>

      <section style={cardStyle}>
        <h2 style={{ fontSize: '1.125rem', fontWeight: 600, margin: '0 0 0.5rem' }}>Autoblog integrations</h2>
        <p style={{ fontSize: '0.875rem', color: mutedColor, marginBottom: '1rem' }}>
          Bearer tokens for inbound autoblog webhooks. Add via direct insert into{' '}
          <code style={{ background: 'var(--color-bg-secondary)', padding: '0.1rem 0.35rem', borderRadius: '0.25rem', fontSize: '0.8em' }}>
            autoblog_integrations
          </code>.
        </p>
        {(integrations ?? []).length === 0 ? (
          <p style={{ fontSize: '0.875rem', color: mutedColor }}>No integrations configured.</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--color-border)' }}>
                <th style={{ textAlign: 'left', padding: '0.5rem 1rem 0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Name</th>
                <th style={{ textAlign: 'left', padding: '0.5rem 1rem 0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Kind</th>
                <th style={{ textAlign: 'right', padding: '0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Requests</th>
              </tr>
            </thead>
            <tbody>
              {(integrations ?? []).map((i) => (
                <tr key={i.id} style={{ borderBottom: '1px solid var(--color-border)' }}>
                  <td style={{ padding: '0.5rem 1rem 0.5rem 0', fontWeight: 500 }}>{i.name}</td>
                  <td style={{ padding: '0.5rem 1rem 0.5rem 0', color: mutedColor }}>{i.kind}</td>
                  <td style={{ padding: '0.5rem 0', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{i.request_count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      <section style={cardStyle}>
        <h2 style={{ fontSize: '1.125rem', fontWeight: 600, margin: '0 0 0.5rem' }}>Recent blog posts</h2>
        {(posts ?? []).length === 0 ? (
          <p style={{ fontSize: '0.875rem', color: mutedColor }}>No posts ingested yet.</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--color-border)' }}>
                <th style={{ textAlign: 'left', padding: '0.5rem 1rem 0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Title</th>
                <th style={{ textAlign: 'left', padding: '0.5rem 1rem 0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Source</th>
                <th style={{ textAlign: 'left', padding: '0.5rem 0', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: mutedColor }}>Published</th>
              </tr>
            </thead>
            <tbody>
              {(posts ?? []).map((p) => (
                <tr key={p.id} style={{ borderBottom: '1px solid var(--color-border)' }}>
                  <td style={{ padding: '0.5rem 1rem 0.5rem 0' }}>
                    <Link href={`/blog/${p.slug}`} style={{ textDecoration: 'underline' }}>{p.title}</Link>
                  </td>
                  <td style={{ padding: '0.5rem 1rem 0.5rem 0', color: mutedColor }}>{p.source}</td>
                  <td style={{ padding: '0.5rem 0', color: mutedColor }}>{p.published_at.slice(0, 10)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </div>
  );
}

// src/routes/admin/+page.svelte
<script>
  let { data } = $props();
  const { email, integrations, posts } = data;

  function fmt(iso) {
    if (!iso) return '—';
    return new Date(iso).toLocaleString();
  }
</script>

<svelte:head>
  <title>Admin — QryptChat</title>
  <meta name="robots" content="noindex, nofollow" />
</svelte:head>

<main class="admin">
  <h1>Admin</h1>
  <p class="who">Logged in as {email}</p>

  <section class="card">
    <h2>Autoblog integrations</h2>
    <p class="hint">
      Bearer tokens for inbound autoblog webhooks. Each token is also the HMAC
      secret for Standard Webhooks signature verification. Add tokens via direct
      database insert into <code>autoblog_integrations</code>.
    </p>
    {#if integrations.length === 0}
      <p class="empty">No integrations configured.</p>
    {:else}
      <table>
        <thead>
          <tr>
            <th>Name</th><th>Kind</th><th class="right">Requests</th><th>Last used</th>
          </tr>
        </thead>
        <tbody>
          {#each integrations as i}
            <tr>
              <td class="bold">{i.name}</td>
              <td class="muted">{i.kind}</td>
              <td class="right mono">{i.request_count}</td>
              <td class="muted">{fmt(i.last_used_at)}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </section>

  <section class="card">
    <h2>Recent blog posts</h2>
    {#if posts.length === 0}
      <p class="empty">No posts ingested yet.</p>
    {:else}
      <table>
        <thead>
          <tr><th>Title</th><th>Source</th><th>Published</th></tr>
        </thead>
        <tbody>
          {#each posts as p}
            <tr>
              <td><a href="/blog/{p.slug}">{p.title}</a></td>
              <td class="muted">{p.source}</td>
              <td class="muted">{p.published_at.slice(0, 10)}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </section>
</main>

<style>
  .admin { max-width: 48rem; margin: 0 auto; padding: 3rem 1rem; display: flex; flex-direction: column; gap: 2rem; }
  h1 { font-size: 2rem; font-weight: 700; margin: 0; }
  .who { margin-top: 0.25rem; font-size: 0.875rem; color: var(--color-muted, #888); }
  .card { border: 1px solid var(--color-border, #333); border-radius: 0.5rem; padding: 1.25rem; }
  h2 { font-size: 1.125rem; font-weight: 600; margin: 0 0 0.5rem; }
  .hint { font-size: 0.875rem; color: var(--color-muted, #888); margin-bottom: 1rem; }
  .empty { font-size: 0.875rem; color: var(--color-muted, #888); }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  th { text-align: left; padding: 0.5rem 1rem 0.5rem 0; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--color-muted, #888); border-bottom: 1px solid var(--color-border, #333); }
  td { padding: 0.5rem 1rem 0.5rem 0; border-bottom: 1px solid var(--color-border, #333); }
  .bold { font-weight: 500; }
  .muted { color: var(--color-muted, #888); }
  .right { text-align: right; }
  .mono { font-variant-numeric: tabular-nums; }
  a { text-decoration: underline; color: var(--color-accent, #6366f1); }
  code { background: var(--color-card, #1a1a2e); padding: 0.1rem 0.35rem; border-radius: 0.25rem; font-size: 0.8em; }
</style>
