// src/lib/components/settings/WebhookSettings.svelte
<script>
	let webhooks = $state([]);
	let url = $state('');
	let events = $state('message.created');
	let loading = $state(false);
	let error = $state('');

	const EVENT_OPTIONS = [
		'message.created',
		'conversation.created',
		'message.deleted'
	];

	async function loadWebhooks() {
		const res = await fetch('/api/webhooks');
		if (res.ok) {
			const data = await res.json();
			webhooks = data.webhooks;
		}
	}

	async function addWebhook() {
		error = '';
		if (!url) return;

		loading = true;
		try {
			const res = await fetch('/api/webhooks', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ url, events: events.split(',').map((e) => e.trim()) })
			});
			const data = await res.json();
			if (!res.ok) {
				error = data.error;
			} else {
				webhooks = [data.webhook, ...webhooks];
				url = '';
			}
		} finally {
			loading = false;
		}
	}

	async function removeWebhook(id) {
		const res = await fetch(`/api/webhooks/${id}`, { method: 'DELETE' });
		if (res.ok) {
			webhooks = webhooks.filter((w) => w.id !== id);
		}
	}

	$effect(() => {
		loadWebhooks();
	});
</script>

<div class="space-y-4">
	<h3 class="text-lg font-semibold">Webhooks</h3>
	<p class="text-sm text-gray-500">Receive HTTP POST notifications when events occur.</p>

	<form onsubmit={(e) => { e.preventDefault(); addWebhook(); }} class="flex flex-col gap-2">
		<input
			type="url"
			bind:value={url}
			placeholder="https://example.com/webhook"
			required
			class="rounded border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-700"
		/>
		<select bind:value={events} class="rounded border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-700">
			{#each EVENT_OPTIONS as opt}
				<option value={opt}>{opt}</option>
			{/each}
		</select>
		{#if error}
			<p class="text-red-500 text-sm">{error}</p>
		{/if}
		<button
			type="submit"
			disabled={loading}
			class="self-start rounded bg-blue-600 px-4 py-2 text-sm text-white hover:bg-blue-700 disabled:opacity-50"
		>
			{loading ? 'Adding...' : 'Add Webhook'}
		</button>
	</form>

	{#if webhooks.length > 0}
		<ul class="divide-y dark:divide-gray-700">
			{#each webhooks as hook (hook.id)}
				<li class="flex items-center justify-between py-2">
					<div class="min-w-0 flex-1">
						<p class="truncate text-sm font-mono">{hook.url}</p>
						<p class="text-xs text-gray-500">{hook.events.join(', ')}</p>
					</div>
					<button
						onclick={() => removeWebhook(hook.id)}
						class="ml-4 text-sm text-red-500 hover:text-red-700"
					>
						Remove
					</button>
				</li>
			{/each}
		</ul>
	{:else}
		<p class="text-sm text-gray-400">No webhooks configured.</p>
	{/if}
</div>

// src/lib/components/settings/WebhookSettings.jsx
'use client';

import { useState, useEffect } from 'react';

const EVENT_OPTIONS = ['message.created', 'conversation.created', 'message.deleted'];

export default function WebhookSettings() {
  const [webhooks, setWebhooks] = useState([]);
  const [url, setUrl] = useState('');
  const [events, setEvents] = useState('message.created');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => { loadWebhooks(); }, []);

  async function loadWebhooks() {
    try {
      const res = await fetch('/api/webhooks', { credentials: 'include' });
      if (res.ok) { const d = await res.json(); setWebhooks(d.webhooks || []); }
    } catch {}
  }

  async function addWebhook(e) {
    e.preventDefault();
    if (!url.trim()) return;
    setLoading(true); setError('');
    try {
      const res = await fetch('/api/webhooks', {
        method: 'POST', credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: url.trim(), events: events.split(',').map((e) => e.trim()) }),
      });
      const data = await res.json();
      if (!res.ok) { setError(data.error || 'Failed to add webhook'); }
      else { setWebhooks([data.webhook, ...webhooks]); setUrl(''); }
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  }

  async function removeWebhook(id) {
    const res = await fetch(`/api/webhooks/${id}`, { method: 'DELETE', credentials: 'include' });
    if (res.ok) setWebhooks(webhooks.filter((w) => w.id !== id));
  }

  return (
    <div>
      {error && <div style={{ background: 'rgba(239,68,68,.1)', color: '#991b1b', border: '1px solid #fca5a5', padding: '.625rem .875rem', borderRadius: '.375rem', fontSize: '.875rem', marginBottom: '.75rem' }}>{error}</div>}

      <form onSubmit={addWebhook} style={{ display: 'flex', flexDirection: 'column', gap: '.75rem', marginBottom: '1.25rem' }}>
        <div>
          <label style={{ display: 'block', fontWeight: 500, marginBottom: '.375rem', fontSize: '.875rem' }}>Webhook URL</label>
          <input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com/webhook" required style={{ width: '100%', padding: '.5rem .75rem', borderRadius: '.375rem', border: '1px solid var(--color-border-primary)', background: 'var(--color-bg-secondary)', color: 'var(--color-text-primary)' }} />
        </div>
        <div>
          <label style={{ display: 'block', fontWeight: 500, marginBottom: '.375rem', fontSize: '.875rem' }}>Events</label>
          <select value={events} onChange={(e) => setEvents(e.target.value)} style={{ width: '100%', padding: '.5rem .75rem', borderRadius: '.375rem', border: '1px solid var(--color-border-primary)', background: 'var(--color-bg-secondary)', color: 'var(--color-text-primary)' }}>
            {EVENT_OPTIONS.map((opt) => <option key={opt} value={opt}>{opt}</option>)}
          </select>
        </div>
        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading ? 'Adding...' : 'Add Webhook'}
        </button>
      </form>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '.5rem' }}>
        {webhooks.length === 0 && <p style={{ color: 'var(--color-text-secondary)', fontSize: '.875rem' }}>No webhooks configured.</p>}
        {webhooks.map((wh) => (
          <div key={wh.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '.75rem', background: 'var(--color-bg-secondary)', border: '1px solid var(--color-border-primary)', borderRadius: '.375rem' }}>
            <div>
              <div style={{ fontSize: '.875rem', fontWeight: 500, color: 'var(--color-text-primary)', wordBreak: 'break-all' }}>{wh.url}</div>
              <div style={{ fontSize: '.75rem', color: 'var(--color-text-secondary)' }}>{Array.isArray(wh.events) ? wh.events.join(', ') : wh.events}</div>
            </div>
            <button onClick={() => removeWebhook(wh.id)} style={{ background: 'none', border: 'none', color: 'var(--color-error)', cursor: 'pointer', padding: '.25rem .5rem', fontSize: '.875rem' }}>Remove</button>
          </div>
        ))}
      </div>
    </div>
  );
}
