// src/lib/components/ChatRequestPromptModal.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();
	let isOpen = true;

	function accept() {
		dispatch('accept');
		isOpen = false;
	}
	function reject() {
		dispatch('reject');
		isOpen = false;
	}
</script>

{#if isOpen}
<div class="modal-overlay">
	<div class="modal-container">
		<h2>Chat Request</h2>
		<p>Do you want to accept this chat request?</p>
		<div class="actions">
			<button class="accept" on:click={accept}>Accept</button>
			<button class="reject" on:click={reject}>Reject</button>
		</div>
	</div>
</div>
{/if}

<style>
.modal-overlay {
	position: fixed;
	inset: 0;
	background: rgba(0,0,0,0.5);
	display: flex;
	align-items: center;
	justify-content: center;
	z-index: 9999;
}
.modal-container {
	background: white;
	border-radius: 12px;
	padding: 2rem;
	box-shadow: 0 8px 32px rgba(0,0,0,0.2);
	text-align: center;
	min-width: 300px;
}
.actions {
	display: flex;
	gap: 1rem;
	justify-content: center;
	margin-top: 1.5rem;
}
.accept {
	background: #3b82f6;
	color: white;
	border: none;
	padding: 0.5rem 1.5rem;
	border-radius: 6px;
	font-weight: 500;
	cursor: pointer;
}
.reject {
	background: #e5e7eb;
	color: #374151;
	border: none;
	padding: 0.5rem 1.5rem;
	border-radius: 6px;
	font-weight: 500;
	cursor: pointer;
}
</style>

// src/lib/components/ChatRequestPromptModal.jsx
'use client';

export default function ChatRequestPromptModal({ request, onAccept, onDecline }) {
  if (!request) return null;
  return (
    <div className="modal-overlay">
      <div className="modal-content">
        <h3>Chat Request</h3>
        <p><strong>{request.fromName}</strong> wants to start a chat with you.</p>
        <div style={{ display: 'flex', gap: '.75rem', marginTop: '1rem' }}>
          <button className="btn btn-primary" onClick={onAccept}>Accept</button>
          <button className="btn btn-secondary" onClick={onDecline}>Decline</button>
        </div>
        <style>{`
          .modal-overlay { position: fixed; inset: 0; background: rgba(0,0,0,.5); display: flex; align-items: center; justify-content: center; z-index: 100; }
          .modal-content { background: var(--color-bg-primary); border-radius: 1rem; padding: 1.5rem; max-width: 400px; width: 100%; }
        `}</style>
      </div>
    </div>
  );
}
