// src/lib/components/ConversationItem.svelte
<script>
	import { createEventDispatcher } from 'svelte';
	import { user } from '$lib/stores/auth.js';

	// Props
	let {
		conversation,
		active = false,
		isRoom = false,
		isNoteToSelf = false
	} = $props();

	const dispatch = createEventDispatcher();

	// Handle click
	function handleClick() {
		dispatch('select', conversation.id);
	}

	// Handle right-click context menu
	function handleContextMenu(event) {
		event.preventDefault();
		// Don't show context menu for note-to-self conversations
		if (isNoteToSelf) {
			return;
		}
		dispatch('contextmenu', event);
	}


	// Format last message time
	function formatTime(/** @type {string | null | undefined} */ timestamp) {
		if (!timestamp) return '';
		
		const date = new Date(timestamp);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffMins = Math.floor(diffMs / 60000);
		const diffHours = Math.floor(diffMs / 3600000);
		const diffDays = Math.floor(diffMs / 86400000);

		if (diffMins < 1) return 'now';
		if (diffMins < 60) return `${diffMins}m`;
		if (diffHours < 24) return `${diffHours}h`;
		if (diffDays < 7) return `${diffDays}d`;
		
		return date.toLocaleDateString();
	}

	// Truncate message content
	function truncateMessage(/** @type {string | null | undefined} */ content, maxLength = 50) {
		if (!content) return '';
		if (content.length <= maxLength) return content;
		return content.substring(0, maxLength) + '...';
	}

	// Truncate conversation ID for debugging
	function truncateConversationId(/** @type {string | null | undefined} */ id) {
		if (!id) return '';
		return id.substring(0, 8);
	}
</script>

<button
	class="conversation-item"
	class:active
	class:is-room={isRoom}
	class:is-note-to-self={isNoteToSelf}
	class:archived={conversation.is_archived}
	onclick={handleClick}
	oncontextmenu={handleContextMenu}
>
	<div class="conversation-avatar">
		{#if isNoteToSelf}
			<div class="note-to-self-icon">
				<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
					<path d="M14,2A8,8 0 0,0 6,10A8,8 0 0,0 14,18A8,8 0 0,0 22,10A8,8 0 0,0 14,2M14,16A6,6 0 0,1 8,10A6,6 0 0,1 14,4A6,6 0 0,1 20,10A6,6 0 0,1 14,16M14,7A3,3 0 0,0 11,10A3,3 0 0,0 14,13A3,3 0 0,0 17,10A3,3 0 0,0 14,7M14,11A1,1 0 0,1 13,10A1,1 0 0,1 14,9A1,1 0 0,1 15,10A1,1 0 0,1 14,11Z M4,6V9H2V4A2,2 0 0,1 4,2H9V4H4V6Z M2,15V20A2,2 0 0,0 4,22H9V20H4V15H2Z"/>
				</svg>
			</div>
		{:else if conversation.avatar_url}
			<img src={conversation.avatar_url} alt={conversation.name} />
		{:else if isRoom}
			<div class="room-icon">
				<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
					<path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
				</svg>
			</div>
		{:else}
			<div class="avatar-placeholder">
				{(conversation.name || 'U').charAt(0).toUpperCase()}
			</div>
		{/if}
	</div>

	<div class="conversation-content">
		<div class="conversation-header">
			<div class="conversation-name">
				{#if isRoom}
					<span class="room-prefix">#</span>
				{/if}
				{conversation.name
					|| (conversation.participants && conversation.participants.length > 0
						? conversation.participants
							.filter(p => p && p.username && p.id !== $user?.id)
							.map(p => p.username)
							.join(', ') || 'Chat'
						: 'Unknown')}
				{#if conversation.unread_count > 0}
					<div class="unread-indicator" title="{conversation.unread_count} unread messages"></div>
				{/if}
				{#if conversation.is_archived}
					<div class="archive-indicator" title="Archived">📦</div>
				{/if}
			</div>
			
			<div class="conversation-meta">
				{#if conversation.last_message_at}
					<div class="conversation-time">
						{formatTime(conversation.last_message_at)}
					</div>
				{/if}
				<div class="conversation-id" title={conversation.id}>
					{truncateConversationId(conversation.id)}
				</div>
			</div>
		</div>

		<div class="conversation-preview">
			{#if conversation.last_message_content}
				<div class="last-message">
					{#if conversation.last_message_sender_username && conversation.type !== 'direct'}
						<span class="sender-name">{conversation.last_message_sender_username}:</span>
					{/if}
					<span class="message-content">
						{truncateMessage(conversation.last_message_content)}
					</span>
				</div>
			{/if}
		</div>
	</div>
</button>

<style>
	.conversation-item {
		width: 100%;
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 0.75rem 1rem;
		background: none;
		border: none;
		cursor: pointer;
		text-align: left;
		transition: background-color 0.2s ease;
		border-radius: 0;
		position: relative;
	}

	.conversation-item:hover {
		background: rgba(0, 0, 0, 0.05);
	}

	.conversation-item.active {
		background: rgba(0, 0, 0, 0.1);
		border-right: 3px solid var(--color-primary-500);
	}

	.conversation-item.is-room {
		padding-left: 1.5rem;
		font-size: 0.875rem;
	}

	.conversation-avatar {
		width: 40px;
		height: 40px;
		border-radius: 50%;
		overflow: hidden;
		flex-shrink: 0;
		position: relative;
	}

	.is-room .conversation-avatar {
		width: 32px;
		height: 32px;
	}

	.conversation-avatar img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.avatar-placeholder {
		width: 100%;
		height: 100%;
		background: var(--color-primary-500);
		color: white;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		font-size: 1rem;
	}

	.is-room .avatar-placeholder {
		font-size: 0.875rem;
	}

	.room-icon {
		width: 100%;
		height: 100%;
		background: var(--color-surface-hover);
		color: var(--color-text-secondary);
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 50%;
	}

	.note-to-self-icon {
		width: 100%;
		height: 100%;
		background: var(--color-primary-100);
		color: var(--color-primary-600);
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 50%;
	}

	.note-to-self-icon svg {
		flex-shrink: 0;
	}

	.conversation-content {
		flex: 1;
		min-width: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.conversation-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.5rem;
	}

	.conversation-name {
		font-weight: 600;
		color: var(--color-text-primary);
		font-size: 0.875rem;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		display: flex;
		align-items: center;
		gap: 0.25rem;
	}

	.room-prefix {
		color: var(--color-text-secondary);
		font-weight: 400;
	}

	.conversation-meta {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		flex-shrink: 0;
	}

	.conversation-time {
		font-size: 0.75rem;
		color: var(--color-text-secondary);
		flex-shrink: 0;
	}

	.conversation-id {
		font-size: 0.625rem;
		color: var(--color-text-secondary);
		opacity: 0.6;
		font-family: monospace;
		background: var(--color-surface-hover);
		padding: 0.125rem 0.25rem;
		border-radius: 0.25rem;
		flex-shrink: 0;
	}

	.conversation-preview {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.5rem;
	}

	.last-message {
		flex: 1;
		min-width: 0;
		font-size: 0.75rem;
		color: var(--color-text-secondary);
		display: flex;
		gap: 0.25rem;
	}

	.sender-name {
		font-weight: 500;
		color: var(--color-text-primary);
		flex-shrink: 0;
	}

	.message-content {
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.unread-indicator {
		width: 8px;
		height: 8px;
		background: var(--color-error);
		border-radius: 50%;
		flex-shrink: 0;
		margin-left: 0.375rem;
		animation: pulse-unread 2s infinite;
	}

	@keyframes pulse-unread {
		0%, 100% {
			opacity: 1;
			transform: scale(1);
		}
		50% {
			opacity: 0.7;
			transform: scale(1.1);
		}
	}

	/* Active state adjustments */
	.conversation-item.active .conversation-name {
		color: var(--color-primary-700);
	}

	.conversation-item.active .last-message {
		color: var(--color-primary-600);
	}

	.conversation-item.active .sender-name {
		color: var(--color-primary-700);
	}

	/* Dark mode support */
	@media (prefers-color-scheme: dark) {
		.conversation-item:hover {
			background: rgba(255, 255, 255, 0.05);
		}

		.conversation-item.active {
			background: rgba(255, 255, 255, 0.1);
		}

		.conversation-item.active .conversation-name {
			color: var(--color-primary-300);
		}

		.conversation-item.active .last-message {
			color: var(--color-primary-400);
		}

		.conversation-item.active .sender-name {
			color: var(--color-primary-300);
		}
	}
</style>

// src/lib/components/ConversationItem.jsx
'use client';

import { useAuthStore } from '@/lib/stores/auth.js';

export default function ConversationItem({ conversation, isActive, onSelect, onContextMenu }) {
  const user = useAuthStore((s) => s.user);

  const name = conversation.name || conversation.conversation_name ||
    (conversation.participants?.find((p) => p.id !== user?.id)?.username || 'Chat');
  const unread = conversation.unread_count || 0;
  const lastMessage = conversation.last_message_preview || '';
  const lastTime = conversation.last_message_at
    ? new Date(conversation.last_message_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : '';

  return (
    <div
      className={`conversation-item${isActive ? ' active' : ''}`}
      onClick={() => onSelect?.(conversation.id)}
      onContextMenu={(e) => { e.preventDefault(); onContextMenu?.(e, conversation); }}
    >
      <div className="conv-avatar">
        {conversation.avatar_url ? (
          <img src={conversation.avatar_url} alt={name} />
        ) : (
          <div className="conv-avatar-placeholder">{name.charAt(0).toUpperCase()}</div>
        )}
        {unread > 0 && <div className="unread-badge">{unread > 99 ? '99+' : unread}</div>}
      </div>
      <div className="conv-info">
        <div className="conv-name-row">
          <span className="conv-name">{name}</span>
          {lastTime && <span className="conv-time">{lastTime}</span>}
        </div>
        {lastMessage && (
          <div className="conv-preview">{lastMessage}</div>
        )}
      </div>

      <style>{`
        .conversation-item { display: flex; align-items: center; gap: .75rem; padding: .75rem 1rem; cursor: pointer; border-radius: .5rem; transition: background-color .15s; position: relative; }
        .conversation-item:hover { background-color: var(--color-bg-secondary); }
        .conversation-item.active { background-color: var(--color-brand-primary); }
        .conversation-item.active .conv-name, .conversation-item.active .conv-preview, .conversation-item.active .conv-time { color: white; }
        .conv-avatar { position: relative; flex-shrink: 0; width: 44px; height: 44px; border-radius: 50%; overflow: hidden; }
        .conv-avatar img { width: 100%; height: 100%; object-fit: cover; }
        .conv-avatar-placeholder { width: 100%; height: 100%; background: var(--color-brand-primary); color: white; display: flex; align-items: center; justify-content: center; font-weight: 600; font-size: 1.125rem; }
        .conversation-item.active .conv-avatar-placeholder { background: rgba(255,255,255,.2); }
        .unread-badge { position: absolute; top: -2px; right: -2px; background: var(--color-error); color: white; font-size: .625rem; font-weight: 700; border-radius: 9999px; min-width: 18px; height: 18px; display: flex; align-items: center; justify-content: center; padding: 0 .25rem; }
        .conv-info { flex: 1; min-width: 0; }
        .conv-name-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: .125rem; }
        .conv-name { font-weight: 600; font-size: .9375rem; color: var(--color-text-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .conv-time { font-size: .75rem; color: var(--color-text-muted); flex-shrink: 0; }
        .conv-preview { font-size: .8125rem; color: var(--color-text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      `}</style>
    </div>
  );
}
