// src/lib/components/EncryptionWarning.jsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { keyManager } from '@/lib/crypto/key-manager.js';

export default function EncryptionWarning() {
  const router = useRouter();
  const [hasKeys, setHasKeys] = useState(true);
  const [checked, setChecked] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    async function check() {
      try {
        await keyManager.initialize();
        setHasKeys(await keyManager.hasUserKeys());
      } catch {
        setHasKeys(false);
      }
      setChecked(true);
    }
    check();
  }, []);

  async function handleGenerate() {
    // New keys give you a fresh identity but make every message that was
    // encrypted to your previous key permanently unreadable. Restoring/uploading
    // existing keys is almost always what the user actually wants.
    const ok = window.confirm(
      'Generate brand-new keys?\n\nYou will NOT be able to read any past messages or files that were encrypted to your previous keys. If you have a backup or an exported key file, use "Upload existing keys" instead.'
    );
    if (!ok) return;
    setGenerating(true);
    setError('');
    try {
      await keyManager.generateUserKeys();
      setHasKeys(true);
    } catch (err) {
      setError(err?.message || 'Failed to generate keys');
    } finally {
      setGenerating(false);
    }
  }

  if (!checked || hasKeys) return null;

  return (
    <div className="encryption-warning">
      <div className="warning-icon">⚠️</div>
      <div className="warning-content">
        <strong>No encryption keys on this device</strong>
        <p>
          This browser doesn&apos;t have your encryption keys, so messages can&apos;t be decrypted or sent
          securely. Upload your existing keys to keep your history, or generate new ones to start fresh.
        </p>
        {error && <p className="warning-error">{error}</p>}
        <div className="warning-actions">
          <button
            type="button"
            className="warn-btn warn-btn-primary"
            onClick={() => router.push('/settings')}
            disabled={generating}
          >
            Upload existing keys
          </button>
          <button
            type="button"
            className="warn-btn warn-btn-secondary"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? 'Generating…' : 'Generate new keys'}
          </button>
        </div>
        <p className="warning-hint">
          Switched browsers or devices? Choose <strong>Upload existing keys</strong> — generating new keys
          loses access to all past messages.
        </p>
      </div>
      <style>{`
        .encryption-warning { display: flex; align-items: flex-start; gap: 1rem; padding: .75rem 1rem; background: rgba(245,158,11,.1); border-bottom: 1px solid #f59e0b; color: #92400e; }
        .warning-icon { font-size: 1.25rem; flex-shrink: 0; line-height: 1.4; }
        .warning-content p { font-size: .875rem; margin-top: .25rem; }
        .warning-error { color: #991b1b; font-weight: 600; }
        .warning-actions { display: flex; gap: .5rem; margin-top: .625rem; flex-wrap: wrap; }
        .warn-btn { padding: .375rem .75rem; font-size: .875rem; border-radius: .375rem; cursor: pointer; border: 1px solid transparent; font-weight: 600; }
        .warn-btn:disabled { opacity: .6; cursor: default; }
        .warn-btn-primary { background: #92400e; color: #fff; }
        .warn-btn-secondary { background: transparent; color: #92400e; border-color: #92400e; }
        .warning-hint { font-size: .75rem; margin-top: .5rem; opacity: .85; }
      `}</style>
    </div>
  );
}

// src/lib/components/EncryptionWarning.svelte
<script>
	import { onMount } from 'svelte';
	import { postQuantumEncryption } from '$lib/crypto/post-quantum-encryption.js';
	import { browser } from '$app/environment';
	
	let showWarning = $state(false);
	let hasKeys = $state(false);
	let checking = $state(true);
	
	onMount(async () => {
		if (!browser) return;
		
		try {
			// Check if user has encryption keys
			await postQuantumEncryption.initialize();
			const publicKey = await postQuantumEncryption.getPublicKey();
			hasKeys = !!publicKey;
			showWarning = !hasKeys;
		} catch (error) {
			console.error('Failed to check encryption keys:', error);
			// If we can't check, assume no keys and show warning
			showWarning = true;
			hasKeys = false;
		} finally {
			checking = false;
		}
	});
	
	function dismissWarning() {
		showWarning = false;
	}
</script>

{#if showWarning && !checking}
	<div class="encryption-warning" role="alert">
		<div class="warning-content">
			<div class="warning-icon">🔐</div>
			<div class="warning-text">
				<h4>Encryption Not Set Up</h4>
				<p>
					You haven't set up end-to-end encryption yet. Without encryption keys, 
					you won't be able to send or receive secure messages.
				</p>
			</div>
		</div>
		
		<div class="warning-actions">
			<a href="/settings" class="btn primary">
				🔑 Set Up Encryption
			</a>
			<button class="btn secondary" onclick={dismissWarning}>
				Dismiss
			</button>
		</div>
		
		<div class="warning-details">
			<p><strong>What you can do:</strong></p>
			<ul>
				<li><strong>Generate new keys:</strong> Create fresh encryption keys in Settings</li>
				<li><strong>Import existing keys:</strong> If you have keys from another device, import them in Settings</li>
				<li><strong>Skip for now:</strong> You can set up encryption later, but messages won't be encrypted</li>
			</ul>
		</div>
	</div>
{/if}

<style>
	.encryption-warning {
		background: linear-gradient(135deg, #fef3cd 0%, #fde68a 100%);
		border: 1px solid #f59e0b;
		border-radius: 0.75rem;
		padding: 1.5rem;
		margin: 1rem 0;
		box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
	}
	
	.warning-content {
		display: flex;
		align-items: flex-start;
		gap: 1rem;
		margin-bottom: 1rem;
	}
	
	.warning-icon {
		font-size: 1.5rem;
		flex-shrink: 0;
		margin-top: 0.125rem;
	}
	
	.warning-text h4 {
		margin: 0 0 0.5rem 0;
		font-size: 1.125rem;
		font-weight: 600;
		color: #92400e;
	}
	
	.warning-text p {
		margin: 0;
		font-size: 0.875rem;
		color: #92400e;
		line-height: 1.5;
	}
	
	.warning-actions {
		display: flex;
		gap: 0.75rem;
		margin-bottom: 1rem;
		flex-wrap: wrap;
	}
	
	.btn {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.625rem 1.25rem;
		border: none;
		border-radius: 0.375rem;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
		text-decoration: none;
		white-space: nowrap;
	}
	
	.btn.primary {
		background: #f59e0b;
		color: white;
	}
	
	.btn.primary:hover {
		background: #d97706;
	}
	
	.btn.secondary {
		background: transparent;
		color: #92400e;
		border: 1px solid #f59e0b;
	}
	
	.btn.secondary:hover {
		background: rgba(245, 158, 11, 0.1);
	}
	
	.warning-details {
		padding: 1rem;
		background: rgba(255, 255, 255, 0.5);
		border-radius: 0.5rem;
		border: 1px solid rgba(245, 158, 11, 0.3);
	}
	
	.warning-details p {
		margin: 0 0 0.75rem 0;
		font-size: 0.875rem;
		font-weight: 600;
		color: #92400e;
	}
	
	.warning-details ul {
		margin: 0;
		padding-left: 1.25rem;
		font-size: 0.8125rem;
		color: #92400e;
		line-height: 1.5;
	}
	
	.warning-details li {
		margin-bottom: 0.5rem;
	}
	
	.warning-details li:last-child {
		margin-bottom: 0;
	}
	
	.warning-details strong {
		font-weight: 600;
	}
	
	/* Responsive design */
	@media (max-width: 640px) {
		.encryption-warning {
			margin: 0.75rem 0;
			padding: 1rem;
		}
		
		.warning-content {
			gap: 0.75rem;
		}
		
		.warning-actions {
			flex-direction: column;
		}
		
		.btn {
			justify-content: center;
		}
	}
</style>
